In [1]:
# ! pip install pandas

In [2]:
import numpy as np 
import pandas as pd

In [3]:
data = pd.read_csv('../dataset/CVEFixes.csv')
df = pd.DataFrame(data)

In [4]:
df.head()

                                                code language      safety
0  package org.bouncycastle.jcajce.provider.asymm...     java  vulnerable
1  <?php\n\n\n\n/**\n\n * ownCloud - user_ldap\n\...      php  vulnerable
2  #!/usr/bin/env python\n\nfrom __future__ impor...       py        safe
3  /* -*- c-basic-offset: 8 -*-\n\n   rdesktop: A...        c        safe
4  <!DOCTYPE html>\n\n<html>\n\n    <head>\n\n   ...     html        safe

In [5]:
df.columns

Index(['code', 'language', 'safety'], dtype='str')

In [6]:
df1=df['code']

In [7]:
df1=df1[1]

In [8]:
print(df1)

<?php



/**

 * ownCloud - user_ldap

 *

 * @author Dominik Schmidt

 * @copyright 2011 Dominik Schmidt dev@dominik-schmidt.de

 *

 * This library is free software; you can redistribute it and/or

 * modify it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE

 * License as published by the Free Software Foundation; either

 * version 3 of the License, or any later version.

 *

 * This library is distributed in the hope that it will be useful,

 * but WITHOUT ANY WARRANTY; without even the implied warranty of

 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 * GNU AFFERO GENERAL PUBLIC LICENSE for more details.

 *

 * You should have received a copy of the GNU Affero General Public

 * License along with this library.  If not, see <http://www.gnu.org/licenses/>.

 *

 */

$params = array('ldap_host', 'ldap_port', 'ldap_dn', 'ldap_agent_password', 'ldap_base', 'ldap_base_users', 'ldap_base_groups', 'ldap_userlist_filter', 'ldap_login_filter', 'ldap_group_filter', 'ldap_display_name', 'ldap_group_display_name', 'ldap_tls', 'ldap_turn_off_cert_check', 'ldap_nocase', 'ldap_quota_def', 'ldap_quota_attr', 'ldap_email_attr', 'ldap_group_member_assoc_attribute', 'ldap_cache_ttl', 'home_folder_naming_rule');



OCP\Util::addscript('user_ldap', 'settings');

OCP\Util::addstyle('user_ldap', 'settings');



if ($_POST) {

	$clearCache = false;

	foreach($params as $param) {

		if(isset($_POST[$param])) {

			$clearCache = true;

			if('ldap_agent_password' == $param) {

				OCP\Config::setAppValue('user_ldap', $param, base64_encode($_POST[$param]));

			} elseif('home_folder_naming_rule' == $param) {

				$value = empty($_POST[$param]) ? 'opt:username' : 'attr:'.$_POST[$param];

				OCP\Config::setAppValue('user_ldap', $param, $value);

			} else {

				OCP\Config::setAppValue('user_ldap', $param, $_POST[$param]);

			}

		}

		elseif('ldap_tls' == $param) {

			// unchecked checkboxes are not included in the post paramters

			OCP\Config::setAppValue('user_ldap', $param, 0);

		}

		elseif('ldap_nocase' == $param) {

			OCP\Config::setAppValue('user_ldap', $param, 0);

		}

		elseif('ldap_turn_off_cert_check' == $param) {

			OCP\Config::setAppValue('user_ldap', $param, 0);

		}

	}

	if($clearCache) {

		$ldap = new \OCA\user_ldap\lib\Connection('user_ldap');

		$ldap->clearCache();

	}

}



// fill template

$tmpl = new OCP\Template( 'user_ldap', 'settings');

foreach($params as $param) {

		$value = OCP\Config::getAppValue('user_ldap', $param,'');

		$tmpl->assign($param, $value);

}



// settings with default values

$tmpl->assign( 'ldap_port', OCP\Config::getAppValue('user_ldap', 'ldap_port', '389'));

$tmpl->assign( 'ldap_display_name', OCP\Config::getAppValue('user_ldap', 'ldap_display_name', 'uid'));

$tmpl->assign( 'ldap_group_display_name', OCP\Config::getAppValue('user_ldap', 'ldap_group_display_name', 'cn'));

$tmpl->assign( 'ldap_group_member_assoc_attribute', OCP\Config::getAppValue('user_ldap', 'ldap_group_member_assoc_attribute', 'uniqueMember'));

$tmpl->assign( 'ldap_agent_password', base64_decode(OCP\Config::getAppValue('user_ldap', 'ldap_agent_password')));

$tmpl->assign( 'ldap_cache_ttl', OCP\Config::getAppValue('user_ldap', 'ldap_cache_ttl', '600'));

$hfnr = OCP\Config::getAppValue('user_ldap', 'home_folder_naming_rule', 'opt:username');

$hfnr = ($hfnr == 'opt:username') ? '' : substr($hfnr, strlen('attr:'));

$tmpl->assign( 'home_folder_naming_rule', $hfnr, '');



return $tmpl->fetchPage();

In [9]:
df.shape

(31194, 3)

In [10]:
print(df['code'].isna().sum())
# If >0, you need to drop or fill them

34

In [11]:
df=df.dropna()

## seeing 10 random coding exampoles and their lables

In [12]:
samples = df.sample(10)
for idx, row in samples.iterrows():
    print(f"\n--- Sample {idx} | Language: {row['language']} | Safety: {row['safety']} ---")
    print(row['code'][:400])  # first 400 chars
    print("...\n")

--- Sample 27551 | Language: php | Safety: safe ---
<?php



namespace Kanboard\Controller;



use Kanboard\Core\Base;

use Kanboard\Core\Controller\AccessForbiddenException;

use Kanboard\Core\Controller\PageNotFoundException;



/**

 * Base Controller

 *

 * @package  Kanboard\Controller

 * @author   Frederic Guillot

 */

abstract class BaseController extends Base

{

    /**

     * Check if the CSRF token from the URL is correct

     *


...


--- Sample 28140 | Language: Other | Safety: vulnerable ---
sbt.version=1.3.7

...


--- Sample 8737 | Language: php | Safety: vulnerable ---
<?php



/*

 * This file is part of the Symfony package.

 *

 * (c) Fabien Potencier <fabien@symfony.com>

 *

 * For the full copyright and license information, please view the LICENSE

 * file that was distributed with this source code.

 */



namespace Symfony\Component\ErrorHandler;



use Psr\Log\LoggerInterface;

use Psr\Log\LogLevel;

use Symfony\Component\ErrorHandler\Error\FatalError;

...


--- Sample 3778 | Language: js | Safety: vulnerable ---
var fs = require('fs')

var path = require('path')

var request = require('teeny-request').teenyRequest

var urlgrey = require('urlgrey')

var jsYaml = require('js-yaml')

var walk = require('ignore-walk')

var execSync = require('child_process').execSync

var validator = require('validator')



var detectProvider = require('./detect')



var version = 'v' + require('../package.json').version



v
...


--- Sample 9341 | Language: Other | Safety: safe ---
.



`ag_ini(

  `IniAgent( [ "multi/private.in.*.test" ],

    $[

      "rewrite" : [

	[ "multi/private\.in\.(.)\.test$", "multi/private.in.%s.test"],

      ],

      "subindent" : "  ",

      "comments": [ "^[ \t]*#.*", "^[ \t]*$" ],

      "sections" : [

        $[

        "begin" : [ "[ \t]*\\[Dialer[ \t]+(.*[^ \t])[ \t]*\\][ \t]*", "[Dialer %s]" ],

	"end" : [ "^[ \t]*\\[End\\][ \t]*$",
...


--- Sample 3676 | Language: Other | Safety: safe ---
package asset.pipeline.servlet





import asset.pipeline.AssetPipelineResponseBuilder

import asset.pipeline.AssetPipelineConfigHolder

import asset.pipeline.AssetHelper

import java.util.logging.Logger

import javax.servlet.FilterChain

import javax.servlet.ServletContext

import javax.servlet.ServletException

import javax.servlet.ServletOutputStream

import javax.servlet.ServletRequest

import
...


--- Sample 4056 | Language: c | Safety: safe ---
/*

 * Copyright (c) 1993, 1994, 1995, 1996

 *	The Regents of the University of California.  All rights reserved.

 *

 * Redistribution and use in source and binary forms, with or without

 * modification, are permitted provided that: (1) source code distributions

 * retain the above copyright notice and this paragraph in its entirety, (2)

 * distributions including binary code include the abo
...


--- Sample 23442 | Language: js | Safety: safe ---
'use strict';



var htmlEscape = require('./htmlEscape');

var is = require('is');

var keys = require('object-keys');



// generates a string for common HTML tag attributes

var attrs = function attrs(a) {

    if (typeof a.id === 'boolean') {

        a.id = a.id ? 'id_' + a.name : null;

    }

    if (is.array(a.classes) && a.classes.length > 0) {

        a['class'] = htmlEscape(a.classes.j
...


--- Sample 25287 | Language: c | Safety: safe ---
/*

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%                                                                             %

%                                                                             %

%                                                                             %

%                     L       AAA   BBBB   EEEEE  L
...


--- Sample 17795 | Language: php | Safety: vulnerable ---
<?php



/**

* ownCloud - bookmarks plugin

*

* @author Arthur Schiwon

* @copyright 2011 Arthur Schiwon blizzz@arthur-schiwon.de

*

* This library is free software; you can redistribute it and/or

* modify it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE

* License as published by the Free Software Foundation; either

* version 3 of the License, or any later version.

*

* This l
...

## Group by language – see 2 examples per language

In [13]:
for lang in df['language'].unique():
    print(f"\n=== Language: {lang} ===")
    lang_samples = df[df['language'] == lang].head(2)
    for _, row in lang_samples.iterrows():
        print(f"Safety={row['safety']} | Code preview:\n{row['code'][:200]}\n")

=== Language: java ===
Safety=vulnerable | Code preview:
package org.bouncycastle.jcajce.provider.asymmetric.dsa;



import java.security.InvalidAlgorithmParameterException;

import java.security.InvalidParameterException;

import java.security.KeyPair;

im

Safety=vulnerable | Code preview:
/*

 * Copyright (c) 2014-2015 VMware, Inc. All Rights Reserved.

 *

 * Licensed under the Apache License, Version 2.0 (the "License"); you may not

 * use this file except in compliance with the Lic


=== Language: php ===
Safety=vulnerable | Code preview:
<?php



/**

 * ownCloud - user_ldap

 *

 * @author Dominik Schmidt

 * @copyright 2011 Dominik Schmidt dev@dominik-schmidt.de

 *

 * This library is free software; you can redistribute it and/or



Safety=safe | Code preview:
<?php



/*

 * This file is part of the Symfony package.

 *

 * (c) Fabien Potencier <fabien@symfony.com>

 *

 * For the full copyright and license information, please view the LICENSE

 * file tha


=== Language: py ===
Safety=safe | Code preview:
#!/usr/bin/env python

from __future__ import division, absolute_import, print_function



__all__ = ['run_main', 'compile', 'f2py_testing']



import os

import sys

import subprocess



from . impor

Safety=vulnerable | Code preview:
# This file is dual licensed under the terms of the Apache License, Version

# 2.0, and the BSD License. See the LICENSE file in the root of this repository

# for complete details.



from __future__


=== Language: c ===
Safety=safe | Code preview:
/* -*- c-basic-offset: 8 -*-

   rdesktop: A Remote Desktop Protocol client.

   Protocol services - Clipboard functions

   Copyright 2003 Erik Forsberg <forsberg@cendio.se> for Cendio AB

   Copyrig

Safety=vulnerable | Code preview:
/*

    ettercap -- GTK+ GUI



    Copyright (C) ALoR & NaGA



    This program is free software; you can redistribute it and/or modify

    it under the terms of the GNU General Public License as p


=== Language: html ===
Safety=safe | Code preview:
<!DOCTYPE html>

<html>

    <head>

        <title>VNC Performance Benchmark</title>

    </head>

    <body>



        Passes: <input id='passes' style='width:50' value=3>&nbsp;



        <input i

Safety=vulnerable | Code preview:
<script src="inject-element-after-load.js"></script>

<link rel="import" href="custom-element.html">

<custom-element></custom-element>



=== Language: h ===
Safety=safe | Code preview:
/*

 * User-mode machine state access

 *

 * Copyright (C) 2007 Red Hat, Inc.  All rights reserved.

 *

 * This copyrighted material is made available to anyone wishing to use,

 * modify, copy, or

Safety=safe | Code preview:
/**

 * @file tree_internal.h

 * @author Radek Krejci <rkrejci@cesnet.cz>

 * @brief libyang internal functions for manipulating with the data model and

 * data trees.

 *

 * Copyright (c) 2015 CES


=== Language: htm ===
Safety=safe | Code preview:
<div

    id="<?= $this->getId() ?>"

    class="field-fileupload style-file-single <?= $singleFile ? 'is-populated' : '' ?> <?= $this->previewMode ? 'is-preview' : '' ?>"

    data-control="fileuploa

Safety=vulnerable | Code preview:
<div

    id="<?= $this->getId() ?>"

    class="field-fileupload style-image-single <?= $singleFile ? 'is-populated' : '' ?> <?= $this->previewMode ? 'is-preview' : '' ?>"

    data-control="fileuplo


=== Language: Other ===
Safety=safe | Code preview:
<%= error_messages_for 'time_entry' %>

<%= back_url_hidden_field_tag %>



<div class="box tabular">

  <% if @time_entry.new_record? %>

    <% if params[:project_id] %>

      <%= hidden_field_tag

Safety=safe | Code preview:
Dragonfly

===========



Dragonfly is a <a href="http://rack.rubyforge.org">Rack</a> framework for on-the-fly image handling.



Ideal for using with Ruby on Rails (2.3 and 3), Sinatra and all that g


=== Language: ts ===
Safety=vulnerable | Code preview:
import { ChannelWrapper } from 'amqp-connection-manager';

import { ConsumeMessage } from 'amqplib';

import { processProjects } from './webhooks/projects';

import { processDataSync } from './webhook

Safety=vulnerable | Code preview:
import {ConverterService, IConverterOptions, JsonSchema, PropertyMetadata} from "@tsed/common";

import {getClass, Store, Type} from "@tsed/core";

import * as mongoose from "mongoose";

import {Schem


=== Language: cc ===
Safety=vulnerable | Code preview:
/*

    Mosh: the mobile shell

    Copyright 2012 Keith Winstein



    This program is free software: you can redistribute it and/or modify

    it under the terms of the GNU General Public License

Safety=vulnerable | Code preview:
#include <qpdf/qpdf-config.h>  // include first for large file support

#include <qpdf/QPDF.hh>



#include <vector>

#include <map>

#include <algorithm>

#include <string.h>

#include <memory.h>






=== Language: cpp ===
Safety=vulnerable | Code preview:
/*

   +----------------------------------------------------------------------+

   | HipHop for PHP                                                       |

   +--------------------------------------

Safety=vulnerable | Code preview:
/*

 * Copyright (c) Facebook, Inc. and its affiliates.

 *

 * This source code is licensed under the MIT license found in the

 * LICENSE file in the root directory of this source tree.

 */



#inc


=== Language: ctp ===
Safety=vulnerable | Code preview:
<div class="confirmation">

	<?php

		echo $this->Form->create('Sighting', array('style' => 'margin:0px;', 'id' => 'PromptForm', 'url' => '/sightings/quickDelete/' . $id . '/' . urlencode($rawId) . '/

Safety=safe | Code preview:
<div class="templates form">

<?php

	echo $this->Form->create('Template');

?>

	<fieldset>

		<legend><?php echo __('Create Template'); ?></legend>

	<?php

		echo ($this->Form->input('name', array


=== Language: coffee ===
Safety=safe | Code preview:
fs     = require 'fs'

path   = require 'path'

util   = require 'util'

Module = require 'module'



# We modified the original process.argv to let node.js load the atom.js,

# we need to restore it

Safety=vulnerable | Code preview:
events = require 'events'

path   = require 'path'

url    = require 'url'

Module = require 'module'



# We modified the original process.argv to let node.js load the

# atom-renderer.js, we need to


=== Language: js ===
Safety=safe | Code preview:
/*

 * Tine 2.0

 *

 * @license     http://www.gnu.org/licenses/agpl.html AGPL Version 3

 * @author      Cornelius Weiss <c.weiss@metaways.de>

 * @copyright   Copyright (c) 2007-2011 Metaways Info

Safety=safe | Code preview:
/**

 * Module dependencies.

 */



var transports = require('./transports');

var Emitter = require('component-emitter');

var debug = require('debug')('engine.io-client:socket');

var index = requi


=== Language: go ===
Safety=vulnerable | Code preview:
// Copyright 2018 Project Harbor Authors

//

// Licensed under the Apache License, Version 2.0 (the "License");

// you may not use this file except in compliance with the License.

// You may obtain

Safety=vulnerable | Code preview:
package auth



import (

	"context"

	"fmt"

	"net/http"

	"net/http/httptest"

	"net/url"

	"testing"

)



// mockOpenShiftProvider is test OpenShift provider that only supports discovery

//

// h


=== Language: S ===
Safety=safe | Code preview:
/*

 *  linux/arch/arm/kernel/entry-armv.S

 *

 *  Copyright (C) 1996,1997,1998 Russell King.

 *  ARM700 fix by Matthew Godbolt (linux-user@willothewisp.demon.co.uk)

 *  nommu support by Hyok S. Ch

Safety=safe | Code preview:
/*

 * Based on arch/arm/lib/clear_user.S

 *

 * Copyright (C) 2012 ARM Ltd.

 *

 * This program is free software; you can redistribute it and/or modify

 * it under the terms of the GNU General Pub


=== Language: jsp ===
Safety=vulnerable | Code preview:
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<%@ taglib uri="http://struts.apache.org/tags-html" prefix="html" %>

<%@ taglib uri="http://struts.apache.org/tags-bean" prefix="bean

Safety=vulnerable | Code preview:
<%--

/*******************************************************************************

 * This file is part of OpenNMS(R).

 *

 * Copyright (C) 2016 The OpenNMS Group, Inc.

 * OpenNMS(R) is Copyrig


=== Language: m ===
Safety=vulnerable | Code preview:
/* SOGoUserSettings.m - this file is part of SOGo

 *

 * Copyright (C) 2009-2014 Inverse inc.

 *

 * This file is free software; you can redistribute it and/or modify

 * it under the terms of the G

Safety=vulnerable | Code preview:
/* SOGoCalendarComponent.m - this file is part of SOGo

 *

 * Copyright (C) 2006-2014 Inverse inc.

 *

 * This file is free software; you can redistribute it and/or modify

 * it under the terms of


=== Language: pm ===
Safety=safe | Code preview:
# --

# Kernel/Modules/CustomerTicketMessage.pm - to handle customer messages

# Copyright (C) 2001-2013 OTRS AG, http://otrs.com/

# --

# $Id: CustomerTicketMessage.pm,v 1.100.2.3 2012-07-01 12:29:4

Safety=vulnerable | Code preview:
package Bundle::DBD::mysql;



use strict;

use warnings;



our $VERSION = '4.038_01';



1;



__END__



=pod



=head1 NAME



Bundle::DBD::mysql



=head1 DESCRIPTION



This package only exists


=== Language: scala ===
Safety=safe | Code preview:
package org.http4s

package server

package staticcontent



import cats.data.{Kleisli, OptionT}

import cats.effect.{ContextShift, Effect}

import cats.implicits._

import java.nio.file.{Path, Paths}

Safety=vulnerable | Code preview:
package org.http4s

package server

package staticcontent



import cats.data.{Kleisli, OptionT}

import cats.effect.Effect



/**

  * Constructs new services to serve assets from Webjars

  */

obje


=== Language: tpl ===
Safety=safe | Code preview:
{$app_version = DevblocksPlatform::strVersionToInt($smarty.const.APP_VERSION)}

{$view_fields = $view->getColumnsAvailable()}

{assign var=results value=$view->getData()}

{assign var=total value=$res

Safety=vulnerable | Code preview:
404: Not Found


=== Language: htaccess ===
Safety=vulnerable | Code preview:
404: Not Found

Safety=vulnerable | Code preview:
404: Not Found


=== Language: json ===
Safety=vulnerable | Code preview:
{

  "name": "keyget",

  "description": "Is nested object modification kit. It can find, get, set, push or call nested properties.",

  "version": "2.2.0",

  "main": "index.js",

  "scripts": {



Safety=vulnerable | Code preview:
{

    "name": "nystudio107/craft-seomatic",

    "description": "SEOmatic facilitates modern SEO best practices & implementation for Craft CMS 3. It is a turnkey SEO system that is comprehensive, pow


=== Language: rb ===
Safety=vulnerable | Code preview:
module Sns::LoginFilter

  extend ActiveSupport::Concern



  included do

    protect_from_forgery except: :remote_login

    skip_before_action :verify_authenticity_token unless SS.config.env.protec

Safety=safe | Code preview:
#encoding: utf-8

# frozen_string_literal: true



module Puma

  class UnsupportedOption < RuntimeError

  end





  # Every standard HTTP code mapped to the appropriate message.  These are

  # use


=== Language: tt ===
Safety=safe | Code preview:
# --

# Copyright (C) 2001-2018 OTRS AG, https://otrs.com/

# --

# This software comes with ABSOLUTELY NO WARRANTY. For details, see

# the enclosed file COPYING for license information (GPL). If you

Safety=vulnerable | Code preview:
[% IF NOT results.size %]

<div class="span2 alert alert-info">The job queue is empty.</div>

[% ELSE %]

<table class="table table-bordered table-condensed table-hover nd_floatinghead">

  <thead>




=== Language: xml ===
Safety=vulnerable | Code preview:
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

         xsi:schemaLocation="http://maven.apache.org/P

Safety=safe | Code preview:
<?xml version='1.0'?> <!--*-nxml-*-->

<!DOCTYPE refentry PUBLIC "-//OASIS//DTD DocBook XML V4.2//EN"

    "http://www.oasis-open.org/docbook/xml/4.2/docbookx.dtd">



<refentry id="flatpak-override">


=== Language: inc ===
Safety=vulnerable | Code preview:
<?php

/* Reminder: always indent with 4 spaces (no tabs). */

// +---------------------------------------------------------------------------+

// | DataBox プラグイン   function.inc からrequire

// | Box シ

Safety=safe | Code preview:
<?php



/*

 +-----------------------------------------------------------------------+

 | program/steps/mail/get.inc                                            |

 |


=== Language: scss ===
Safety=safe | Code preview:
// shared styles used

// on both the login and

// create account modals

.login-modal,

.create-account {

  #login-buttons:not(.hidden) {

    display: flex;

    flex: 0 1 auto;

    flex-directio

Safety=vulnerable | Code preview:
// shared styles used

// on both the login and

// create account modals

.login-modal,

.create-account {

  #login-buttons:not(.hidden) {

    display: flex;

    flex: 0 1 auto;

    flex-directio


=== Language: cxx ===
Safety=safe | Code preview:
/* Copyright (C) 2002-2005 RealVNC Ltd.  All Rights Reserved.

 * Copyright 2009-2014 Pierre Ossman for Cendio AB

 *

 * This is free software; you can redistribute it and/or modify

 * it under the

Safety=safe | Code preview:
/*

 * Copyright (C) 2004 Red Hat Inc.

 * Copyright (C) 2005 Martin Koegler

 * Copyright (C) 2010 TigerVNC Team

 *

 * This is free software; you can redistribute it and/or modify

 * it under


=== Language: t ===
Safety=vulnerable | Code preview:
#!./perl -w



$|=1;   # outherwise things get mixed up in output



BEGIN {

	chdir 't' if -d 't';

	require './test.pl';

    set_up_inc( qw '../lib ../ext/re' );

	eval 'require Config'; # assume d

Safety=safe | Code preview:
# --

# Copyright (C) 2001-2016 OTRS AG, http://otrs.com/

# --

# This software comes with ABSOLUTELY NO WARRANTY. For details, see

# the enclosed file COPYING for license information (AGPL). If you


=== Language: vim ===
Safety=safe | Code preview:
" Test for options



function! Test_whichwrap()

  set whichwrap=b,s

  call assert_equal('b,s', &whichwrap)



  set whichwrap+=h,l

  call assert_equal('b,s,h,l', &whichwrap)



  set whichwrap+=h,

Safety=vulnerable | Code preview:
" Tests for autocommands



source shared.vim

source check.vim

source term_util.vim



func s:cleanup_buffers() abort

  for bnr in range(1, bufnr('$'))

    if bufloaded(bnr) && bufnr('%') != bnr




=== Language: hh ===
Safety=safe | Code preview:
/*

 * Copyright © 2007,2008,2009,2010  Red Hat, Inc.

 * Copyright © 2010,2012,2013  Google, Inc.

 *

 *  This is part of HarfBuzz, a text shaping library.

 *

 * Permission is hereby granted, with

Safety=vulnerable | Code preview:
/*

 *  Copyright (c) 2010 The WebM project authors. All Rights Reserved.

 *

 *  Use of this source code is governed by a BSD-style license

 *  that can be found in the LICENSE banner below

 *  An


=== Language: sh ===
Safety=vulnerable | Code preview:
#!/bin/bash

# BEGIN_ICS_COPYRIGHT8 ****************************************

#

# Copyright (c) 2015, Intel Corporation

#

# Redistribution and use in source and binary forms, with or without

# m

Safety=safe | Code preview:
#!/bin/bash

node tests/testHas.js

node tests/testGet.js

node tests/testExports.js

node tests/testSet.js

node tests/testVulnerability.js


=== Language: rs ===
Safety=vulnerable | Code preview:
// Copyright 2012-2014 The Rust Project Developers. See the COPYRIGHT

// file at the top-level directory of this distribution and at

// http://rust-lang.org/COPYRIGHT.

//

// Licensed under the Apa

Safety=safe | Code preview:
// Copyright (c) The Libra Core Contributors

// SPDX-License-Identifier: Apache-2.0



use codespan::{ByteIndex, CodeMap, Span};

use codespan_reporting::{emit, termcolor::Buffer, Diagnostic, Label,


=== Language: jelly ===
Safety=vulnerable | Code preview:
<!--

The MIT License



Copyright (c) 2004-2009, Sun Microsystems, Inc., Kohsuke Kawaguchi, Tom Huybrechts



Permission is hereby granted, free of charge, to any person obtaining a copy

of this sof

Safety=vulnerable | Code preview:
<!--

The MIT License



Copyright (c) 2004-2011, Sun Microsystems, Inc., Kohsuke Kawaguchi, Seiji Sogabe, Andrew Bayer



Permission is hereby granted, free of charge, to any person obtaining a copy



=== Language: yaml ===
Safety=safe | Code preview:
name: "hello"

version: "0.1.0"

usage: "usage"

description: |-

  description

command: "$HELM_PLUGIN_SELF/hello.sh"

ignoreFlags: true

hooks:

  install: "echo installing..."


Safety=vulnerable | Code preview:
404: Not Found


=== Language: cs ===
Safety=vulnerable | Code preview:
// Shared.cs

// ------------------------------------------------------------------

//

// Copyright (c) 2006-2011 Dino Chiesa.

// All rights reserved.

//

// This code module is part of DotNetZip,

Safety=vulnerable | Code preview:
// Copyright (c) Microsoft Corporation. All rights reserved.

// Licensed under the MIT license.

using System;

using System.Collections.Generic;

using System.Diagnostics;

using System.IO;

using S


=== Language: phpt ===
Safety=safe | Code preview:
--TEST--

Bug #73737 (Crash when parsing a tag format)

--SKIPIF--

<?php if (!extension_loaded('exif')) print 'skip exif extension not available';?>

--FILE--

<?php

	$exif = exif_thumbnail(__DIR__

Safety=safe | Code preview:
--TEST--

Bug #72799: wddx_deserialize null dereference in php_wddx_pop_element

--SKIPIF--

<?php

if (!extension_loaded('wddx')) {

    die('skip. wddx not available');

}

?>

--FILE--

<?php



$x


=== Language: as ===
Safety=safe | Code preview:
/*

 * jPlayer Plugin for jQuery JavaScript Library

 * http://www.jplayer.org

 *

 * Copyright (c) 2009 - 2013 Happyworm Ltd

 * Dual licensed under the MIT and GPL licenses.

 *  - http://www.opens

Safety=vulnerable | Code preview:
/**

 * Plupload.as

 *

 * Copyright 2009, Moxiecode Systems AB

 * Released under GPL License.

 *

 * License: http://www.plupload.com/license

 * Contributing: http://www.plupload.com/contributing


=== Language: yml ===
Safety=safe | Code preview:
name: 'Git Tag Annotation'

description: 'Get the annotation associated with a git tag'

author: 'Eric Cornelissen'



inputs:

  tag:

    description: 'tag of interest (defaults to the GITHUB_REF en

Safety=vulnerable | Code preview:
404: Not Found


=== Language: cgi ===
Safety=vulnerable | Code preview:
#!/usr/local/bin/perl

# Show an HTML editor window



$trust_unknown_referers = 1;

require './file-lib.pl';

do '../ui-lib.pl';

$disallowed_buttons{'edit'} && &error($text{'ebutton'});

&ReadParse(

Safety=safe | Code preview:
#!/usr/local/bin/perl

# search.cgi

# Display a list of packages where the name or description matches some string



require './software-lib.pl';

&ReadParse();



$in{'search'} || &error($text{'sea


=== Language: spec ===
Safety=vulnerable | Code preview:
%global USE_FIPSCHECK true

%global USE_LIBCAP_NG true

%global USE_LABELED_IPSEC true

%global USE_CRL_FETCHING true

%global USE_DNSSEC true

%global USE_NM true

%global USE_LINUX_AUDIT true



%gl

Safety=vulnerable | Code preview:
Summary: Openswan IPsec implementation

Name: openswanX

Version: 2.6.50



# Openswan -pre/-rc nomenclature has to co-exist with hyphen paranoia

%define srcpkgver %(echo %{version} | tr -s '_' '-')



=== Language: phtml ===
Safety=safe | Code preview:
<?php

$odd_row = true;

$type = $collation = $func = $value = array();

/**

 * Get already set search criteria (if any)

 */



// Displays column rows for search criteria input

for ($i = 0; $i < 4

Safety=vulnerable | Code preview:
<div id="tablestatistics">

    <?php $odd_row = false; ?>

    <fieldset>

        <legend><?= __('Information'); ?></legend>

        <p> <strong> <?= __('Table comments: ') ?> </strong>




=== Language: conf ===
Safety=safe | Code preview:

## Compare vulnerable vs fixed (if both exist for same CVE

In [14]:
print(df['safety'].value_counts())
print(df['safety'].unique())

safety
vulnerable    15592
safe          15568
Name: count, dtype: int64
<StringArray>
['vulnerable', 'safe']
Length: 2, dtype: str

In [15]:
vuln_df = df[df['safety'] == 0]   # or whatever the vulnerable value is
fixed_df = df[df['safety'] == 1]

print(f"Number of vulnerable rows: {len(vuln_df)}")
print(f"Number of fixed rows: {len(fixed_df)}")

Number of vulnerable rows: 0
Number of fixed rows: 0

In [16]:
print("Unique safety values:", df['safety'].unique())
print("\nValue counts:\n", df['safety'].value_counts())
print("\nData type:", df['safety'].dtype)

Unique safety values: <StringArray>
['vulnerable', 'safe']
Length: 2, dtype: str

Value counts:
 safety
vulnerable    15592
safe          15568
Name: count, dtype: int64

Data type: str

## 📊 Interactive (Jupyter) view – searchable table

In [17]:
from IPython.display import display, HTML
# Show first 15 rows with truncated code
df_display = df.copy()
df_display['code_short'] = df_display['code'].str[:200] + "..."
display(HTML(df_display[['code_short', 'language', 'safety']].head(15).to_html()))

## 💾 Save examples to files for manual review (e.g., to design RAG chunks)

In [18]:
import os
os.makedirs("code_review", exist_ok=True)

for i, (idx, row) in enumerate(df.iterrows()):
    if i >= 20:
        break
    label = "vulnerable" if row['safety'] == 0 else "fixed"
    fname = f"code_review/{label}_{row['language']}_{i}.txt"
    with open(fname, "w") as f:
        f.write(f"Language: {row['language']}\nSafety: {row['safety']}\n\n{row['code']}")

## how many languages are there

In [19]:
# Get unique language names
languages = df['language'].unique()
print(languages)

<StringArray>
[    'java',      'php',       'py',        'c',     'html',        'h',
      'htm',    'Other',       'ts',       'cc',      'cpp',      'ctp',
   'coffee',       'js',       'go',        'S',      'jsp',        'm',
       'pm',    'scala',      'tpl', 'htaccess',     'json',       'rb',
       'tt',      'xml',      'inc',     'scss',      'cxx',        't',
      'vim',       'hh',       'sh',       'rs',    'jelly',     'yaml',
       'cs',     'phpt',       'as',      'yml',      'cgi',     'spec',
    'phtml',     'conf',      'sql',       'pl',      'lua',      'css']
Length: 48, dtype: str

## cleaning the code for making the vectors

- striping the code to produce a better chunk

In [20]:
df = df[df["code"].str.strip() != ""]

##  mkaing the Vernulability understanding 
- CVEfixes database 
- CVEfixes.csv 

## Fix Knowledge (MOST IMPORTANT)
For this i will use to data-repositories 
- Fix Knowledge (MOST IMPORTANT)
- cvedataset-patches 
- security_fixes_high_confidence.jsonl
- 🧠 Purpose:

        Teach system:

        how real vulnerabilities are fixed in real world

```
                USER CODE
                     ↓
        ┌────────────────────────┐
        │ SAST + TAINT ENGINE    │
        └──────────┬─────────────┘
                   ↓
        Vulnerability Type + Flow
                   ↓
     ┌─────────────────────────────┐
     │  CVEFixes INDEX (DB 1)      │  ← “what is wrong”
     └──────────┬──────────────────┘
                ↓
     ┌─────────────────────────────┐
     │ CVE PATCH INDEX (DB 2)      │  ← “how to fix”
     └──────────┬──────────────────┘
                ↓
            LLM GENERATION
                ↓
        FIXED + VALIDATED CODE
```

## loding the other data sets ---- phase(1) 
- --> making the columns sync and the data use able so the rag does not hallucinates

In [21]:
# ! pip install unidiff

In [22]:
import os
import pandas as pd
import json
import sqlite3
from pathlib import Path
from unidiff import PatchSet   # optional: only if you want to parse raw patches

# ======================== CONFIGURATION =========================
DATA_PATH = "../dataset/"
DATASETS = [
    "cvedataset-patches",
    "CVEFixes.csv",
    "security_fixes_high_confidence.jsonl",
    "CVEfixes_v1.0.8.db"
]

# ======================== LOADING FUNCTIONS =====================
def load_dataset(file_name):
    """Load a single dataset (CSV, JSONL, SQLite, or directory of patches)."""
    path = os.path.join(DATA_PATH, file_name)

    if not os.path.exists(path):
        print(f"❌ Path does not exist: {path}")
        return pd.DataFrame() if not isinstance({}, dict) else {}

    # CSV
    if file_name.endswith(".csv"):
        try:
            print(f"📄 Loading CSV: {file_name}")
            return pd.read_csv(path)
        except Exception as e:
            print(f"❌ Error reading CSV {file_name}: {e}")
            return pd.DataFrame()

    # JSONL
    elif file_name.endswith(".jsonl"):
        try:
            print(f"📄 Loading JSONL: {file_name}")
            data = []
            with open(path, "r", encoding="utf-8") as f:
                for line in f:
                    data.append(json.loads(line))
            return pd.DataFrame(data)
        except Exception as e:
            print(f"❌ Error reading JSONL {file_name}: {e}")
            return pd.DataFrame()

    # SQLite database
    elif file_name.endswith(".db"):
        try:
            print(f"🗄️ Loading DB: {file_name}")
            conn = sqlite3.connect(path)
            tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
            db_data = {}
            for table in tables["name"]:
                print(f"→ Loading table: {table}")
                db_data[table] = pd.read_sql(f"SELECT * FROM {table}", conn)
            conn.close()
            return db_data
        except Exception as e:
            print(f"❌ Error reading DB {file_name}: {e}")
            return {}

    # Directory (for patch files)
    elif os.path.isdir(path):
        print(f"📂 Loading directory: {file_name}")
        rows = []
        for f in os.listdir(path):
            full_path = os.path.join(path, f)
            if f.endswith(".patch"):
                try:
                    with open(full_path, "r", encoding="utf-8", errors="ignore") as pf:
                        content = pf.read()
                    parts = Path(f).stem.split('_')
                    commit_hash = parts[-1] if len(parts) > 0 else "unknown"
                    repo = "_".join(parts[1:-1]) if len(parts) > 2 else "unknown"
                    rows.append({
                        "file_name": f,
                        "commit_hash": commit_hash,
                        "repo": repo,
                        "patch_content": content,
                        "type": "patch"
                    })
                except Exception as e:
                    print(f"❌ Error reading patch {f}: {e}")
            elif f.endswith(".csv"):
                try:
                    df_temp = pd.read_csv(full_path)
                    rows.extend(df_temp.to_dict('records'))
                except Exception as e:
                    print(f"❌ Error reading {f}: {e}")
            elif f.endswith(".jsonl"):
                try:
                    with open(full_path, "r", encoding="utf-8") as file:
                        for line in file:
                            rows.append(json.loads(line))
                except Exception as e:
                    print(f"❌ Error reading {f}: {e}")
            else:
                print(f"⚠️ Skipping unsupported file: {f}")
        if not rows:
            print("❌ No valid data found in directory!")
            return pd.DataFrame()
        return pd.DataFrame(rows)

    else:
        print(f"⚠️ Unsupported format: {file_name}")
        return pd.DataFrame()


# ======================== MAIN LOADING LOOP ======================
loaded_data = {}
for d in DATASETS:
    print("\n==============================")
    print(f"Loading: {d}")
    data = load_dataset(d)
    loaded_data[d] = data

# ======================== INSPECT LOADED DATA ====================
print("\n\n===== DATA SUMMARY =====")
for key, value in loaded_data.items():
    print(f"\n--- Dataset Key: '{key}' ---")
    if isinstance(value, pd.DataFrame):
        print(f"  ✅ Shape: {value.shape}")
        print(f"  🧭 Columns: {value.columns.tolist()}")
    elif isinstance(value, dict):
        print(f"  🗄️ SQLite DB with tables:")
        for table_name, table_df in value.items():
            print(f"     - Table: '{table_name}' (shape {table_df.shape})")
    else:
        print(f"  ⚠️ Unknown type: {type(value)}")

# ======================== EXTRACT USEFUL DATAFRAMES ==============
# 1. High‑confidence JSONL (best source)
high_conf_df = loaded_data.get('security_fixes_high_confidence.jsonl')
if isinstance(high_conf_df, pd.DataFrame):
    print(f"\n✅ High‑confidence JSONL loaded: {high_conf_df.shape}")
else:
    print("\n⚠️ High‑confidence JSONL not available")
    high_conf_df = pd.DataFrame()  # empty fallback

# 2. Raw patches (if you need to parse them)
raw_patches_df = loaded_data.get('cvedataset-patches')
if isinstance(raw_patches_df, pd.DataFrame):
    print(f"✅ Raw patches loaded: {raw_patches_df.shape}")
else:
    raw_patches_df = pd.DataFrame()

# 3. SQLite tables – SAFE access (no KeyError)
db_dict = loaded_data.get('CVEfixes_v1.0.8.db')
if isinstance(db_dict, dict):
    print(f"\n✅ SQLite DB loaded with {len(db_dict)} tables")
    # List available tables – use whatever exists
    table_names = list(db_dict.keys())
    print("   Available tables:", table_names)
    
    # Try to assign common table names – but only if they exist
    cves_table = db_dict.get('cves') or db_dict.get('CVE') or db_dict.get('cve')
    commits_table = db_dict.get('commits') or db_dict.get('Commit')
    # Add more as needed
    
    if cves_table is not None:
        print(f"   ✅ Using table '{cves_table.name if hasattr(cves_table, 'name') else '?'}' as CVE metadata (shape {cves_table.shape})")
    else:
        print("   ⚠️ No CVE metadata table found – skipping enrichment")
        cves_table = pd.DataFrame()
else:
    cves_table = pd.DataFrame()
    commits_table = pd.DataFrame()

# ======================== CLEANING HIGH‑CONFIDENCE DATAFRAME =====
def clean_high_confidence(df):
    """Basic cleaning for the JSONL dataset."""
    if df.empty:
        return df
    # Keep only rows with vulnerable and patched code
    required_cols = ['vulnerable_code', 'patched_code']
    for col in required_cols:
        if col not in df.columns:
            print(f"⚠️ Column '{col}' missing in JSONL – cannot clean")
            return df
    # Drop nulls
    df = df.dropna(subset=required_cols)
    # Remove empty strings
    df = df[df['vulnerable_code'].str.strip() != '']
    df = df[df['patched_code'].str.strip() != '']
    # Deduplicate
    df = df.drop_duplicates(subset=['vulnerable_code', 'patched_code'])
    # Optional: filter by language (if column exists)
    if 'language' in df.columns:
        allowed = ['php', 'java', 'python', 'c', 'cpp', 'javascript', 'go', 'ruby']
        df = df[df['language'].isin(allowed)]
    return df

clean_jsonl = clean_high_confidence(high_conf_df)
print(f"\n🧹 Cleaned JSONL shape: {clean_jsonl.shape}")

# ======================== ENRICH WITH CVSS/CWE (if available) ====
if not cves_table.empty and not clean_jsonl.empty:
    # Example: merge on cve_id (adjust column names as needed)
    # First, find the CVE ID column in clean_jsonl
    cve_col_jsonl = None
    for col in ['cve_id', 'CVE', 'cve']:
        if col in clean_jsonl.columns:
            cve_col_jsonl = col
            break
    # Find the CVE ID column in cves_table
    cve_col_cves = None
    for col in ['cve_id', 'CVE', 'cve']:
        if col in cves_table.columns:
            cve_col_cves = col
            break
    
    if cve_col_jsonl and cve_col_cves:
        # Merge CVSS and CWE (adjust column names)
        cvss_col = 'cvss_v3_score' if 'cvss_v3_score' in cves_table.columns else 'cvss_score'
        cwe_col = 'cwe_id' if 'cwe_id' in cves_table.columns else 'cwe'
        keep_cols = [cve_col_cves, cvss_col, cwe_col] + (['description'] if 'description' in cves_table.columns else [])
        enrich_df = cves_table[keep_cols].copy()
        clean_jsonl = clean_jsonl.merge(enrich_df, left_on=cve_col_jsonl, right_on=cve_col_cves, how='left')
        print(f"✅ Enriched with CVE metadata: {clean_jsonl.shape}")
    else:
        print("⚠️ Could not find CVE ID column for merging")
else:
    print("⚠️ Skipping enrichment – missing CVE table or JSONL")

# ======================== FINAL DATAFRAME FOR RAG ================
# This is the DataFrame you will use to build your vector index
vuln_fix_pairs = clean_jsonl

if vuln_fix_pairs.empty:
    print("\n⚠️ No usable data found. Consider parsing raw patches as fallback.")
    # Optionally, you could parse raw_patches_df here into vuln/fix pairs
else:
    print(f"\n🎯 Ready for RAG indexing: {vuln_fix_pairs.shape} rows")
    print("Columns:", vuln_fix_pairs.columns.tolist())

# ======================== OPTIONAL: EXPORT TO CSV ================
# vuln_fix_pairs.to_csv("cleaned_vuln_fix_pairs.csv", index=False)

==============================
Loading: cvedataset-patches
📂 Loading directory: cvedataset-patches

==============================
Loading: CVEFixes.csv
📄 Loading CSV: CVEFixes.csv

==============================
Loading: security_fixes_high_confidence.jsonl
📄 Loading JSONL: security_fixes_high_confidence.jsonl

==============================
Loading: CVEfixes_v1.0.8.db
❌ Path does not exist: ../dataset/CVEfixes_v1.0.8.db


===== DATA SUMMARY =====

--- Dataset Key: 'cvedataset-patches' ---
  ✅ Shape: (32019, 5)
  🧭 Columns: ['file_name', 'commit_hash', 'repo', 'patch_content', 'type']

--- Dataset Key: 'CVEFixes.csv' ---
  ✅ Shape: (31194, 3)
  🧭 Columns: ['code', 'language', 'safety']

--- Dataset Key: 'security_fixes_high_confidence.jsonl' ---
  ✅ Shape: (8407, 15)
  🧭 Columns: ['cve_id', 'language', 'cwe_ids', 'root_cause', 'confidence_score', 'commit_hash', 'commit_msg', 'patch_id', 'file_path', 'func_name', 'vulnerable_code', 'patched_code', 'diff', 'category', 'analysis']

--- Dataset Key: 'CVEfixes_v1.0.8.db' ---
  🗄️ SQLite DB with tables:

✅ High‑confidence JSONL loaded: (8407, 15)
✅ Raw patches loaded: (32019, 5)

✅ SQLite DB loaded with 0 tables
   Available tables: []
   ⚠️ No CVE metadata table found – skipping enrichment

🧹 Cleaned JSONL shape: (844, 15)
⚠️ Skipping enrichment – missing CVE table or JSONL

🎯 Ready for RAG indexing: (844, 15) rows
Columns: ['cve_id', 'language', 'cwe_ids', 'root_cause', 'confidence_score', 'commit_hash', 'commit_msg', 'patch_id', 'file_path', 'func_name', 'vulnerable_code', 'patched_code', 'diff', 'category', 'analysis']

In [24]:
df_raw = loaded_data['security_fixes_high_confidence.jsonl']
print("Original shape:", df_raw.shape)

Original shape: (8407, 15)

In [25]:
# Copy to avoid modifying the original
df_clean = df_raw.copy()

# Keep only rows with non‑empty vulnerable and patched code
df_clean = df_clean.dropna(subset=['vulnerable_code', 'patched_code'])
df_clean = df_clean[df_clean['vulnerable_code'].str.strip() != '']
df_clean = df_clean[df_clean['patched_code'].str.strip() != '']

# Remove exact duplicates (same vulnerable + patched code)
df_clean = df_clean.drop_duplicates(subset=['vulnerable_code', 'patched_code'])

# Optional: keep only certain languages (adjust list as needed)
allowed_langs = ['php', 'java', 'python', 'c', 'cpp', 'javascript', 'go', 'ruby', 'c#', 'swift']
df_clean = df_clean[df_clean['language'].isin(allowed_langs)]

print("Cleaned shape:", df_clean.shape)

Cleaned shape: (844, 15)

In [29]:
# Check what columns are actually in CVEFixes.csv
cve_meta = loaded_data['CVEFixes.csv']
print("Columns in CVEFixes.csv:")
print(cve_meta.columns.tolist())
print("\nFirst few rows:")
print(cve_meta.head())

Columns in CVEFixes.csv:
['code', 'language', 'safety']

First few rows:
                                                code language      safety
0  package org.bouncycastle.jcajce.provider.asymm...     java  vulnerable
1  <?php\n\n\n\n/**\n\n * ownCloud - user_ldap\n\...      php  vulnerable
2  #!/usr/bin/env python\n\nfrom __future__ impor...       py        safe
3  /* -*- c-basic-offset: 8 -*-\n\n   rdesktop: A...        c        safe
4  <!DOCTYPE html>\n\n<html>\n\n    <head>\n\n   ...     html        safe

In [30]:
cve_meta = loaded_data['CVEFixes.csv']
print("Columns in CVEFixes.csv:", cve_meta.columns.tolist())

Columns in CVEFixes.csv: ['code', 'language', 'safety']

In [28]:
df_clean = df_clean.merge(
    cve_meta[['actual_cve_column', 'actual_cvss_column', 'actual_cwe_column']],
    left_on='cve_id',          # the column in df_clean that holds CVE ID
    right_on='actual_cve_column',
    how='left'
)

KeyError: "None of [Index(['actual_cve_column', 'actual_cvss_column', 'actual_cwe_column'], dtype='str')] are in the [columns]"